name: A2A Docker Build and Push

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

env:
  IMAGE_NAME: cnoe-io/agent-webex

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=a2a-latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=branch,prefix=a2a-
            type=ref,event=tag,prefix=a2a-
            type=sha,format=short,prefix=a2a-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and Push A2A Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./build/Dockerfile.a2a
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max