import { User } from "@/types/user"
import { Task, Subtask } from "@/types/task"

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Sarah Chen",
    email: "sarah.chen@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    skills: ["React", "TypeScript", "UI/UX", "Frontend"],
    engagement: {
      completedTasks: 24,
      avgResponseTime: 2.5,
      activeSubtasks: 3,
      totalContributions: 89,
    },
    skillDistribution: [
      { skill: "Frontend", value: 95 },
      { skill: "Design", value: 85 },
      { skill: "Backend", value: 45 },
      { skill: "DevOps", value: 30 },
      { skill: "Testing", value: 70 },
    ],
  },
  {
    id: "user-2",
    name: "Marcus Rodriguez",
    email: "marcus.r@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus",
    skills: ["Node.js", "Python", "API Design", "Backend"],
    engagement: {
      completedTasks: 31,
      avgResponseTime: 1.8,
      activeSubtasks: 5,
      totalContributions: 112,
    },
    skillDistribution: [
      { skill: "Frontend", value: 55 },
      { skill: "Design", value: 35 },
      { skill: "Backend", value: 95 },
      { skill: "DevOps", value: 75 },
      { skill: "Testing", value: 80 },
    ],
  },
  {
    id: "user-3",
    name: "Emma Watson",
    email: "emma.w@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma",
    skills: ["AWS", "Docker", "Kubernetes", "DevOps"],
    engagement: {
      completedTasks: 19,
      avgResponseTime: 3.2,
      activeSubtasks: 2,
      totalContributions: 67,
    },
    skillDistribution: [
      { skill: "Frontend", value: 40 },
      { skill: "Design", value: 25 },
      { skill: "Backend", value: 70 },
      { skill: "DevOps", value: 98 },
      { skill: "Testing", value: 65 },
    ],
  },
  {
    id: "user-4",
    name: "Liam O'Brien",
    email: "liam.o@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Liam",
    skills: ["Jest", "Cypress", "QA", "Testing"],
    engagement: {
      completedTasks: 28,
      avgResponseTime: 2.1,
      activeSubtasks: 4,
      totalContributions: 95,
    },
    skillDistribution: [
      { skill: "Frontend", value: 65 },
      { skill: "Design", value: 45 },
      { skill: "Backend", value: 60 },
      { skill: "DevOps", value: 50 },
      { skill: "Testing", value: 95 },
    ],
  },
  {
    id: "user-5",
    name: "Priya Patel",
    email: "priya.p@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya",
    skills: ["Figma", "Design Systems", "UI/UX", "Prototyping"],
    engagement: {
      completedTasks: 22,
      avgResponseTime: 2.8,
      activeSubtasks: 3,
      totalContributions: 78,
    },
    skillDistribution: [
      { skill: "Frontend", value: 70 },
      { skill: "Design", value: 98 },
      { skill: "Backend", value: 25 },
      { skill: "DevOps", value: 20 },
      { skill: "Testing", value: 55 },
    ],
  },
  {
    id: "user-6",
    name: "Alex Kim",
    email: "alex.k@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    skills: ["PostgreSQL", "MongoDB", "Database Design", "Backend"],
    engagement: {
      completedTasks: 26,
      avgResponseTime: 2.0,
      activeSubtasks: 3,
      totalContributions: 88,
    },
    skillDistribution: [
      { skill: "Frontend", value: 45 },
      { skill: "Design", value: 30 },
      { skill: "Backend", value: 92 },
      { skill: "DevOps", value: 68 },
      { skill: "Testing", value: 72 },
    ],
  },
]

export const mockTasks: Task[] = [
  {
    id: "task-1",
    title: "Implement User Authentication System",
    description: "Build a secure authentication system with JWT tokens, OAuth integration, and multi-factor authentication support.",
    status: "open",
    priority: "high",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    progress: 45,
    tags: ["security", "backend", "frontend"],
    assignedMembers: [mockUsers[1], mockUsers[0], mockUsers[3]],
    metrics: [
      {
        metric: "Impact",
        value: 95,
        description: "Critical for user data security",
        category: "impact",
      },
      {
        metric: "Urgency",
        value: 85,
        description: "Needed for upcoming launch",
        category: "urgency",
      },
      {
        metric: "Complexity",
        value: 75,
        description: "Requires security expertise",
        category: "complexity",
      },
      {
        metric: "Dependencies",
        value: 60,
        description: "Blocks several features",
        category: "dependencies",
      },
      {
        metric: "Risk",
        value: 80,
        description: "Security vulnerabilities possible",
        category: "risk",
      },
    ],
    subtasks: [
      {
        id: "subtask-1-1",
        title: "Design authentication flow and database schema",
        description: "Create detailed design for auth system including user tables, session management, and token storage",
        status: "completed",
        assignedTo: [mockUsers[1]],
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        estimatedHours: 8,
      },
      {
        id: "subtask-1-2",
        title: "Implement JWT token generation and validation",
        description: "Build secure token system with refresh tokens and expiration handling",
        status: "in_progress",
        assignedTo: [mockUsers[1]],
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        estimatedHours: 12,
      },
      {
        id: "subtask-1-3",
        title: "Build login and registration UI components",
        description: "Create responsive forms with validation and error handling",
        status: "in_progress",
        assignedTo: [mockUsers[0]],
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        estimatedHours: 10,
      },
      {
        id: "subtask-1-4",
        title: "Write comprehensive authentication tests",
        description: "Unit and integration tests for all auth flows",
        status: "open",
        assignedTo: [mockUsers[3]],
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        estimatedHours: 16,
      },
    ],
  },
  {
    id: "task-2",
    title: "Redesign Dashboard UI",
    description: "Modernize the dashboard with new design system, improved data visualization, and responsive layouts",
    status: "open",
    priority: "medium",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    progress: 20,
    tags: ["design", "frontend", "ux"],
    assignedMembers: [mockUsers[4], mockUsers[0]],
    metrics: [
      {
        metric: "Impact",
        value: 70,
        description: "Improves user experience",
        category: "impact",
      },
      {
        metric: "Urgency",
        value: 50,
        description: "Nice to have soon",
        category: "urgency",
      },
      {
        metric: "Complexity",
        value: 60,
        description: "Moderate design work",
        category: "complexity",
      },
      {
        metric: "Dependencies",
        value: 30,
        description: "Few dependencies",
        category: "dependencies",
      },
      {
        metric: "Risk",
        value: 40,
        description: "Low technical risk",
        category: "risk",
      },
    ],
    subtasks: [
      {
        id: "subtask-2-1",
        title: "Create design mockups in Figma",
        description: "Design all dashboard views with new style guide",
        status: "completed",
        assignedTo: [mockUsers[4]],
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        estimatedHours: 20,
      },
      {
        id: "subtask-2-2",
        title: "Implement new component library",
        description: "Build reusable React components based on designs",
        status: "in_progress",
        assignedTo: [mockUsers[0]],
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        estimatedHours: 24,
      },
      {
        id: "subtask-2-3",
        title: "Integrate data visualization charts",
        description: "Add interactive charts and graphs",
        status: "open",
        assignedTo: [],
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        estimatedHours: 16,
      },
    ],
  },
  {
    id: "task-3",
    title: "API Performance Optimization",
    description: "Optimize database queries, implement caching, and improve API response times",
    status: "open",
    priority: "high",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    progress: 65,
    tags: ["backend", "performance", "database"],
    assignedMembers: [mockUsers[1], mockUsers[5], mockUsers[2]],
    metrics: [
      {
        metric: "Impact",
        value: 85,
        description: "Significantly improves user experience",
        category: "impact",
      },
      {
        metric: "Urgency",
        value: 90,
        description: "Current performance is poor",
        category: "urgency",
      },
      {
        metric: "Complexity",
        value: 80,
        description: "Requires deep optimization work",
        category: "complexity",
      },
      {
        metric: "Dependencies",
        value: 70,
        description: "Affects multiple services",
        category: "dependencies",
      },
      {
        metric: "Risk",
        value: 65,
        description: "Could cause regressions",
        category: "risk",
      },
    ],
    subtasks: [
      {
        id: "subtask-3-1",
        title: "Profile and identify slow queries",
        description: "Use profiling tools to find bottlenecks",
        status: "completed",
        assignedTo: [mockUsers[5]],
        createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        estimatedHours: 8,
      },
      {
        id: "subtask-3-2",
        title: "Optimize database indexes",
        description: "Add appropriate indexes and optimize queries",
        status: "completed",
        assignedTo: [mockUsers[5]],
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        estimatedHours: 12,
      },
      {
        id: "subtask-3-3",
        title: "Implement Redis caching layer",
        description: "Add caching for frequently accessed data",
        status: "in_progress",
        assignedTo: [mockUsers[1]],
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
        estimatedHours: 16,
      },
      {
        id: "subtask-3-4",
        title: "Set up monitoring and alerts",
        description: "Configure performance monitoring tools",
        status: "open",
        assignedTo: [mockUsers[2]],
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        estimatedHours: 10,
      },
    ],
  },
  {
    id: "task-4",
    title: "Mobile App MVP",
    description: "Build initial version of mobile app with core features",
    status: "closed",
    priority: "high",
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    progress: 100,
    tags: ["mobile", "react-native", "frontend"],
    assignedMembers: [mockUsers[0], mockUsers[4]],
    metrics: [],
    subtasks: [
      {
        id: "subtask-4-1",
        title: "Set up React Native project",
        description: "Initialize project with necessary dependencies",
        status: "completed",
        assignedTo: [mockUsers[0]],
        createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString(),
        estimatedHours: 8,
      },
      {
        id: "subtask-4-2",
        title: "Build core screens",
        description: "Implement main app screens",
        status: "completed",
        assignedTo: [mockUsers[0]],
        createdAt: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
        estimatedHours: 40,
      },
      {
        id: "subtask-4-3",
        title: "Design mobile UI",
        description: "Create mobile-specific designs",
        status: "completed",
        assignedTo: [mockUsers[4]],
        createdAt: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString(),
        estimatedHours: 24,
      },
    ],
  },
  {
    id: "task-5",
    title: "Documentation Portal",
    description: "Create comprehensive documentation site for developers and users",
    status: "closed",
    priority: "medium",
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    progress: 100,
    tags: ["documentation", "frontend"],
    assignedMembers: [mockUsers[0]],
    metrics: [],
    subtasks: [
      {
        id: "subtask-5-1",
        title: "Set up documentation framework",
        description: "Choose and configure documentation tool",
        status: "completed",
        assignedTo: [mockUsers[0]],
        createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
        estimatedHours: 6,
      },
      {
        id: "subtask-5-2",
        title: "Write API documentation",
        description: "Document all API endpoints",
        status: "completed",
        assignedTo: [mockUsers[0]],
        createdAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        estimatedHours: 20,
      },
      {
        id: "subtask-5-3",
        title: "Create user guides",
        description: "Write end-user documentation",
        status: "completed",
        assignedTo: [mockUsers[0]],
        createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        estimatedHours: 16,
      },
    ],
  },
]
